### ISSUE TITLE
Could the .rmd files be uploaded instead of the html docs?

### ISSUE THREAD

**Issue by ben-williams** [NCEAS/pfx-groundfish#3]

**Comment by reblake** [comment]
Which files does this refer to?

**Comment by ben-williams** [comment]
All the Gfish_Diversity_MS_1 files are .html the source files would be mo' better

**Comment by reblake** [comment]
There are no Rmd files for these html files.  These html files are generated by the Authorea site, and then pushed to GitHub by that site.  We're using Authorea to write the diversity manuscript.  If you'd like to view it, you can do so here: https://www.authorea.com/users/93870/articles/114080/_show_article
Please, please, please don't move any of these files.  Authorea requires a certain file structure.  Thanks!
